"""Intermediate Representations (IR) for the tensor compiler.

This package provides layered IRs:
- cpp_ast: Low-level C++ AST for imperative code generation
- cpp_codegen: C++ code generator using Visitor pattern
- tir: Tensor-level IR for loop nest optimization
- lowering: Graph IR to TIR lowering
- tir_to_cpp: TIR to C++ AST conversion
"""

from .cpp_ast import (
    ASTNode,
    ASTVisitor,
    ASTTransformer,
    Expr,
    Stmt,
    Identifier,
    Literal,
    BinaryOp,
    UnaryOp,
    TernaryOp,
    Call,
    Index,
    Cast,
    ExprStmt,
    Assign,
    VarDecl,
    Block,
    ForLoop,
    WhileLoop,
    If,
    Return,
    FunctionDecl,
    StructDecl,
    Include,
    Define,
    Pragma,
    RawCode,
    Program,
)

from .cpp_codegen import CodegenVisitor, generate_cpp

from .tir import (
    TIRNode,
    TIRExpr,
    TIRStmt,
    TIRVisitor,
    TIRTransformer,
    Var as TIRVar,
    Const as TIRConst,
    Binary as TIRBinary,
    Unary as TIRUnary,
    Ternary as TIRTernary,
    CallExpr as TIRCallExpr,
    BufferLoad,
    BufferStore,
    For as TIRFor,
    Block as TIRBlock,
    IfStmt,
    Allocate,
    LetStmt,
    Buffer,
    PrimFunc,
    IRModule,
    LoopAnnotation,
)

from .lowering import GraphLowering, LoweringContext

from .tir_to_cpp import TIRToCppConverter, convert_tir_to_cpp

__all__ = [
    "ASTNode",
    "ASTVisitor",
    "ASTTransformer",
    "Expr",
    "Stmt",
    "Identifier",
    "Literal",
    "BinaryOp",
    "UnaryOp",
    "TernaryOp",
    "Call",
    "Index",
    "Cast",
    "ExprStmt",
    "Assign",
    "VarDecl",
    "Block",
    "ForLoop",
    "WhileLoop",
    "If",
    "Return",
    "FunctionDecl",
    "StructDecl",
    "Include",
    "Define",
    "Pragma",
    "RawCode",
    "Program",
    "CodegenVisitor",
    "generate_cpp",
    "TIRNode",
    "TIRExpr",
    "TIRStmt",
    "TIRVisitor",
    "TIRTransformer",
    "TIRVar",
    "TIRConst",
    "TIRBinary",
    "TIRUnary",
    "TIRTernary",
    "TIRCallExpr",
    "BufferLoad",
    "BufferStore",
    "TIRFor",
    "TIRBlock",
    "IfStmt",
    "Allocate",
    "LetStmt",
    "Buffer",
    "PrimFunc",
    "IRModule",
    "LoopAnnotation",
    "GraphLowering",
    "LoweringContext",
    "TIRToCppConverter",
    "convert_tir_to_cpp",
]
